name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 22
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --frozen-lockfile
      - name: Check
        run: vp run check
      - name: Test
        run: vp test
      - name: Build
        run: vp pack
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vp exec semantic-release
